import { createFileRoute } from "@tanstack/react-router";
import { FinalCta, PageIntro, PortraitPlaceholder, SectionLabel } from "@/components/site";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Us — Outlier Synapse" }, { name: "description", content: "Learn how Outlier Synapse approaches business growth as a connected, measurable system." },
  { property: "og:title", content: "About Outlier Synapse" }, { property: "og:description", content: "A systems-first studio for measurable customer acquisition and sustainable business growth." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage(){return <><PageIntro index="01" eyebrow="About Us" title="Growth becomes predictable when the system is clear." description="Outlier Synapse brings strategy, acquisition, automation, and conversion design into one coherent operating model."/><section className="border-b border-border"><div className="site-container grid grid-cols-12 gap-10 py-16 lg:py-20"><div className="col-span-12 lg:col-span-5"><SectionLabel>02 — Our Story</SectionLabel><h2 className="font-serif text-3xl">Built around a systems-first belief.</h2></div><div className="col-span-12 space-y-5 text-base leading-relaxed text-muted-foreground lg:col-span-6 lg:col-start-7"><p>Most businesses do not lack marketing activity. They lack a clear structure connecting attention, follow-up, conversion, and learning.</p><p>Outlier Synapse exists to design that structure. The official company story, milestones, and operating history remain editable until confirmed.</p></div></div></section><section className="border-b border-border"><div className="site-container py-16 lg:py-20"><SectionLabel>03 — The Difference</SectionLabel><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-3">{[{t:"One connected system",c:"Channels, messages, follow-up, and conversion work from the same blueprint."},{t:"Automation with intent",c:"Technology supports the customer journey instead of adding disconnected tools."},{t:"Measured improvement",c:"The system is designed to reveal what works and where to optimize next."}].map((x,i)=><div key={x.t} className="bg-background p-8"><span className="text-xs text-ice">0{i+1}</span><h2 className="mt-8 font-serif text-2xl">{x.t}</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{x.c}</p></div>)}</div></div></section><section><div className="site-container grid grid-cols-12 gap-10 py-16 lg:py-20"><div className="col-span-7 sm:col-span-4 lg:col-span-3"><PortraitPlaceholder label="Vineeth portrait placeholder"/></div><div className="col-span-12 lg:col-span-7 lg:col-start-5"><SectionLabel>04 — Founder</SectionLabel><h2 className="font-serif text-4xl">Vineeth</h2><p className="mt-2 text-xs uppercase text-smoke">Founder · official biography pending</p><p className="mt-6 max-w-2xl leading-relaxed text-muted-foreground">This space is reserved for Vineeth&apos;s verified founder story, experience, perspective, and reason for building Outlier Synapse.</p></div></div></section><FinalCta/></>}