import { createFileRoute } from "@tanstack/react-router";
import { MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageIntro, SectionLabel } from "@/components/site";

export const Route = createFileRoute("/contact")({ validateSearch: (search: Record<string, unknown>) => ({ channel: search["channel"] === "whatsapp" ? "whatsapp" : undefined }), head: () => ({ meta: [
  { title: "Contact — Outlier Synapse" }, { name: "description", content: "Book a strategy call with Outlier Synapse to discuss your acquisition, automation, website, or growth goals." },
  { property: "og:title", content: "Contact Outlier Synapse" }, { property: "og:description", content: "Start a conversation about building a predictable growth system for your business." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage(){const {channel}=Route.useSearch(); return <><PageIntro index="01" eyebrow="Contact" title="Let’s design the next growth system." description="Share where your business is now, what is slowing growth, and what you want the system to make possible."/><section><div className="site-container grid grid-cols-12 gap-10 py-16 lg:py-20"><div className="col-span-12 lg:col-span-7"><SectionLabel>02 — Strategy Call Enquiry</SectionLabel><form className="grid gap-5 sm:grid-cols-2" onSubmit={(event)=>event.preventDefault()}><label className="text-sm">Name<Input className="mt-2 h-11" name="name" placeholder="Your name"/></label><label className="text-sm">Business email<Input className="mt-2 h-11" name="email" type="email" placeholder="name@company.com"/></label><label className="text-sm sm:col-span-2">Company<Input className="mt-2 h-11" name="company" placeholder="Company name"/></label><label className="text-sm sm:col-span-2">Message<Textarea className="mt-2 min-h-40" name="message" placeholder="Tell us about your goals and current growth challenges."/></label><div className="sm:col-span-2"><Button type="submit" size="lg">Send enquiry</Button><p className="mt-3 text-xs text-smoke">Form submission is a design preview and is not connected yet.</p></div></form></div><aside className="col-span-12 lg:col-span-4 lg:col-start-9"><SectionLabel>03 — Direct Contact</SectionLabel><div className={`rounded-md border p-6 ${channel ? "border-ice bg-secondary" : "border-border"}`}><MessageCircle className="size-6 text-ice"/><h2 className="mt-6 font-serif text-2xl">WhatsApp Consultation</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Start a direct conversation once the official WhatsApp number is confirmed.</p><Button variant="outline" className="mt-6 w-full">WhatsApp number — placeholder</Button></div><dl className="mt-8 divide-y divide-border border-y border-border text-sm"><div className="py-4"><dt className="text-xs uppercase text-smoke">Email</dt><dd className="mt-1">Placeholder</dd></div><div className="py-4"><dt className="text-xs uppercase text-smoke">Phone</dt><dd className="mt-1">Placeholder</dd></div><div className="py-4"><dt className="text-xs uppercase text-smoke">Location</dt><dd className="mt-1">Placeholder</dd></div></dl></aside></div></section></>}